### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Jwilson97** [jaykali/maskphish#10]
Hey there, I am a hobbyist and new comer to the ethical hacking world and I tried to paste my ngrok link and I got this error. Was wondering if you could help me figure it out:) 

`./maskphish.sh: 4: Bad substitution`

**Comment by jaykali** [comment]
Which shell you are using ? MaskPhish is currently working with ZSH only. If you are using bash then Please modify the 1st line of the code from "**#!/bin/zsh**" to "**#!/bin/bash**".

**Comment by jaykali** [comment]
Without using ./maskphish.sh please use `bash maaskphish.sh` This will solve your problem.

**Comment by nobody199192** [comment]
His tool is not working properly

**Comment by jaykali** [comment]
Please use the updated tool. We have updated this the new version is 2.0
