### ISSUE TITLE
MaskPhishing not working

### ISSUE THREAD

**Issue by mjain234** [jaykali/maskphish#100]
Hi there
I just installed Advphishing tool and Maskphish tool but ended up with this, can you help me out here!!
https://user-images.githubusercontent.com/70900505/178328787-dcb92623-c2f4-4471-b616-c4f771fbdf3b.mp4

**Comment by mjain234** [comment]
I tried using Zphisher tool, the link which i get from Zphisher is working but when I used Maskphishing Tool, it is saying "Sorry, the link is either broken, or etc"

**Comment by jaykali** [comment]
Please share MaskPhish video or screenshot that we can understand the error.. Thanks

**Comment by Lolalipop** [comment]
why is maskphish not working?
![Screenshot_2022-08-25-22-46-52-30](https://user-images.githubusercontent.com/111861623/186734544-8d02db14-102d-4b2d-946c-bed72957d58a.jpg)
