### ISSUE TITLE
@blacklisted urls are getting generated 

### ISSUE THREAD

**Issue by khansaad1275** [jaykali/maskphish#101]
I am trying to mask a link but i don't know why, bu the tool is not working, it is generating @blaclisted url as you can see in the below picture. can anyone explain if they know about this error.

![image](https://user-images.githubusercontent.com/32749921/181218522-6496c30d-4d5d-4209-9df7-b77a1ce10e1d.png)

**Comment by jaykali** [comment]
You are using older version... Please update it #13
