### ISSUE TITLE
Can  I mask Beef hook.js urls, I mean beef hook urls are blocked by browsers mostly. 

### ISSUE THREAD

**Issue by RohaanShahab** [jaykali/maskphish#116]
Can  I mask Beef hook.js urls, I mean beef hook urls are blocked by browsers mostly.  How? It says enter a valid url whenever I try.

**Comment by jaykali** [comment]
If a browser blocking bEEF URL then it also block MaskPhish URL. Because MaskPhish didn't change the URL. It just hide the URL, but the target webpage remains same. Thanks
