### ISSUE TITLE
Blacklisted Long URL

### ISSUE THREAD

**Issue by mjain234** [jaykali/maskphish#13]
Whenever I try to make a real link through Maskphish tool,it says at very last "@blacklisted long URL".  here is the screenshot of the issue 👇
![Screenshot_20201222-040601](https://user-images.githubusercontent.com/70900505/102830011-60d90b80-440e-11eb-90d3-2bc12c17f65a.png)

**Comment by jaykali** [comment]
Hey you are using older version of MaskPhish. Please remove it and get the new version.

**Comment by mjain234** [comment]
How can I get the update of Maskphish?

**Comment by jaykali** [comment]
First delete this maskphish folder by using rm command (Linux basics). Then again git clone this repo.

**Comment by mjain234** [comment]
Which repo?

**Comment by jaykali** [comment]
open your termux. and type following commands:

`rm -rf maskphish`
`git clone https://github.com/jaykali/maskphish`
`cd maskphish`
`bash maskphish.sh`

**Comment by jaykali** [comment]
You will be updated.
