### ISSUE TITLE
طريقة تثبيت الاختراق

### ISSUE THREAD

**Issue by Abdu38hkem** [jaykali/maskphish#130]
### Discussed in https://github.com/jaykali/maskphish/discussions/129

<div type='discussions-op-text'>

<sup>Originally posted by **Abdu38hkem** August  2, 2023</sup>
كيف يمكنني معرفة انا الضحية قد وقع في الفخ</div>

**Comment by jaykali** [comment]
لم يغير "Maskphish" عنوان URL ، ولكنه يستخدم فقط بعض تقنيات الهندسة الاجتماعية لجعل الرابط شرعيًا للضحايا واستخدام اختصار url. إذا رأيت علامة @ على عنوان URL ، فيمكن أن يكون عنوان URL مقنعًا. تتمثل أفضل الممارسات في عدم النقر فوق أي عنوان URL تم الحصول عليه من شخص لا تثق به.

(Translate by Google)
