### ISSUE TITLE
i tried like using ur script to cover this link [rickroll]

### ISSUE THREAD

**Issue by Wackolmao** [jaykali/maskphish#133]
https://rgb.cyperlands.net-https://rgb.cyperlands.net/2@is.gd/F2L0LF it gave that and i tried entering it in my browser see if it worked but it said it didnt work then i tried https://rgb.cyperlands.net/2@is.gd/F2L0LF it has no https and said the file did not exist

**Comment by jaykali** [comment]
Can you provide the screenshot of maskphish page?

**Comment by jaykali** [comment]
Your main link is also said that file not found. MaskPhish don't change the link it just redirect links.
