### ISSUE TITLE
hello how do i solve the blacklisted url

### ISSUE THREAD

**Issue by chuoh** [jaykali/maskphish#137]
![maskphish](https://github.com/jaykali/maskphish/assets/154726333/2005e13a-ff92-4c3e-8cfc-29167ac8add6)

**Comment by mymadhavyadav07** [comment]
Hey @chuoh,
Actually, the Phishing-url which you have entered is in the internal blacklist of the url-shortener service used by this tool.
One of the reasons of blacklisting that specific url would may be because of the unethical use of that specific url.

That was all from my side!😀

Thanks

**Comment by jaykali** [comment]
use it with VPN. Your country must blocking our url short technology.
