### ISSUE TITLE
Issues with Masking

### ISSUE THREAD

**Issue by Herqules** [jaykali/maskphish#139]
Hi, no matter what i try i seem to have an issue with the masking feature? Either it never works (i.e. isnt generated, returning the local / generic link) or it simply doesnt follow through to the actual link. Is there any update for this or should i just reinstall again?

**Comment by jaykali** [comment]
screenshot please

**Comment by Herqules** [comment]
Trying to use a simple self-hosted page and use Maskphish to camouflage it but so far nothing has worked (image included below). I started experiementing with Zphisher because its native masking tool never seemed to work but this only works with preexisting links if that makes sense.

<img width="716" alt="SCR-20240123-pejq" src="https://github.com/jaykali/maskphish/assets/131825586/81d21713-2c63-47a9-8880-37b14c96e3c8">

**Comment by jaykali** [comment]
you can't use your localhost. You need to host it somewhere or use ngrok/serveo.net like services. Thanks. We are not in the same network so we can't access your localhost. You need to come on the internet.
