### ISSUE TITLE
Database insert failed

### ISSUE THREAD

**Issue by Snopboy9999** [jaykali/maskphish#140]
database insert failed error

**Comment by jaykali** [comment]
screenshot please

**Comment by Snopboy9999** [comment]
![insert failed](https://github.com/jaykali/maskphish/assets/145567433/96b957f5-e7c7-4c89-a636-dfde38b14946)

**Comment by jaykali** [comment]
Use a VPN. Hope this problem will be solved. I think your ISP is banning our services. Thanks
