### ISSUE TITLE
Sorry, the URL you entered is on our internal blacklist

### ISSUE THREAD

**Issue by Boots-cyber** [jaykali/maskphish#143]
It always says Sorry, the URL you entered is on our internal blacklis I have tried with many kinds of links but it always says that alone.![Screenshot_2024_0215_225930.jpg](https://github.com/jaykali/maskphish/assets/151758255/cd2a40f4-2540-4949-bcc3-72bab83a86fc)

**Comment by jaykali** [comment]
using a VPN will solve your problem
