### ISSUE TITLE
Not working on Facebook

### ISSUE THREAD

**Issue by xenonxander** [jaykali/maskphish#15]
I sent a link thru messenger. but if you click the link. webpage is not available. but working on Google chrome.

**Comment by jaykali** [comment]
It is working on chrome but not in firefox. If your given link is working then MaskPhish will work. MaskPhish just shroten the link in a special way nothing else. We are sure that it is the problem of link.

Thanks,

**Comment by claybenjamin24** [comment]
Nope it's working .if u know how to use ..
I tested it myself it's 100% working
