### ISSUE TITLE
Generated link won't work

### ISSUE THREAD

**Issue by distortedkid** [jaykali/maskphish#29]
So I succesfully mask the ngrok link into a "legit " one but if I open the generated link it says that the link is broken or has expired for instance on instagram.

**Comment by ivyglenn78** [comment]
Same here

**Comment by jaykali** [comment]
Hello @ivyglenn78 & @distortedkid , 

Can you guys provide screenshot?

**Comment by distortedkid** [comment]
![issue3](https://user-images.githubusercontent.com/81994115/114315222-a416d180-9b06-11eb-9429-bcdaf3a22073.PNG)
So the ngrok link works just fine
![issue2](https://user-images.githubusercontent.com/81994115/114315237-ac6f0c80-9b06-11eb-83d9-6d372ab8a04a.PNG)
If I mask it with maskphish it just won't work anymore
![issue1](https://user-images.githubusercontent.com/81994115/114315243-b85ace80-9b06-11eb-9eae-7fa62f68538e.PNG)

**Comment by jaykali** [comment]
You should not use `/` before social engineering words. just use post9642952 Then it will work for sure.
