### ISSUE TITLE
Can not work properly what can I do

### ISSUE THREAD

**Issue by maruf-shah** [jaykali/maskphish#3]
![Screenshot_20201014-094819_NetHunter_Terminal](https://user-images.githubusercontent.com/61610519/95955881-56533200-0e1f-11eb-8735-ac38c60b76c2.png)

**Comment by jaykali** [comment]
You need to install curl. Before using it you should install curl by using following command:
`apt-get install curl`

Then it will work finely. Thanks.

**Comment by maruf-shah** [comment]
Thank you for your kind cooperation

**Comment by jaykali** [comment]
On your screenshot I can see an Bengali app? Apni Bangali?

**Comment by maruf-shah** [comment]
Yes I'm from Bangladesh
From where you are?

**Comment by jaykali** [comment]
I am from West Bengal. Jai Bangla

**Comment by maruf-shah** [comment]
Oh, that's good to know you, can you speak bangli dear...

**Comment by jaykali** [comment]
ha. Obbosoi. Ami bangla parbo na keno? Otai toh matribhasha. Bolen apni kemon asen?

**Comment by maruf-shah** [comment]
Valo asi vai , apni kemon asen r apni ki koren janale valo lagbe

**Comment by jaykali** [comment]
Ami house wife. But interested in cybersecurity & ethical hacking

**Comment by maruf-shah** [comment]
Oh that's good, which subject have you completed your graduation?

**Comment by jaykali** [comment]
Ami graduation kori nai. Accha pore kotha hobe
