### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MRFRYE009** [jaykali/maskphish#35]
Whenever i try to use this tool this happens u can c urself some matrix like animation
![IMG_20210430_205527](https://user-images.githubusercontent.com/75823631/116718035-30762f00-a9f7-11eb-8c30-353cfc159dc3.jpg)
More info I'm trying it with camphish and with ngrok local host =3333

**Comment by jaykali** [comment]
You have used "-jatt" as a social engineering word. Please use the "-" between words not in front or end of the words. You can use simple jatt or jatt-videos.

That's it. Thanks.

**Comment by MRFRYE009** [comment]
Can i use nothing

**Comment by MRFRYE009** [comment]
I used exact same and still same issue

**Comment by jaykali** [comment]
![maskphish](https://user-images.githubusercontent.com/62602243/116772640-11ff4a80-aa6e-11eb-8689-a7e868843d5a.png)
Here it is perfectly working... `https://m.youtube.com` not _https://m.youtube.com/_

Yes you can use without social engineering works. Just leave it blank and press <kbd>Enter</kbd>.
