### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by MRFRYE009** [jaykali/maskphish#36]
Sorry for opening this but can u make a video tutorial I also saw ur blog but it didn't worked for me i also saw some video but not helpful or just Tell me what to type in social eng if i want give any example  also tell domain name from which to conceal

**Comment by jaykali** [comment]
Sorry we don't have an YouTube channel now. We will clear things on our github redme but for now, Please show us some errors you are getting.

**Comment by MRFRYE009** [comment]
You have any social media??

**Comment by jaykali** [comment]
[Twitter](https://twitter.com/KaliLinux_in)

**Comment by MRFRYE009** [comment]
Now I don't need that tool anymore anyways thx for help

**Comment by jaykali** [comment]
Its good to hear.
