### ISSUE TITLE
the masked link isnt working

### ISSUE THREAD

**Issue by Siddharth0328** [jaykali/maskphish#44]
The unmasked link works successfully over other devices ,but once I mask it and send it to other devices it shows "connection was reset", "too much connections" or "failed to load". Moreover maskphish does not create the complete link when its used over wifi .

**Comment by jaykali** [comment]
Please provide us screenshot.

**Comment by Siddharth0328** [comment]
![WhatsApp Image 2021-06-09 at 12 57 18 PM (1)](https://user-images.githubusercontent.com/84778812/121311926-81e0da80-c922-11eb-97f5-f4ca3a78a98a.jpeg)
I used the first link in the mask phish
![WhatsApp Image 2021-06-09 at 12 57 18 PM](https://user-images.githubusercontent.com/84778812/121312018-991fc800-c922-11eb-8dba-fc07407c1e2a.jpeg)
Then I used the masked and unmasked link and this is shown
![WhatsApp Image 2021-06-09 at 12 56 13 PM](https://user-images.githubusercontent.com/84778812/121312142-b5bc0000-c922-11eb-9e6a-6e057184decb.jpeg)
![WhatsApp Image 2021-06-09 at 12 56 28 PM](https://user-images.githubusercontent.com/84778812/121312166-bb194a80-c922-11eb-8e27-ecfef5059297.jpeg)

**Comment by jaykali** [comment]
https://user-images.githubusercontent.com/62602243/121350374-39d4ae80-c948-11eb-916d-c3b90b58645a.mp4

Everything is perfect. We have used the is.gd link you provided. It's showing error due to connection problem with tunnel. From our end everything is perfect. Maskphish doesn't change the URL it just redirect to your link as you can see on the video we had attached.

Try it again. It will work perfectly if there was no ssh tunnel issue.

**Comment by jaykali** [comment]
Here is the link of the video
http://0x0.st/-_CJ.mp4

**Comment by Siddharth0328** [comment]
I'm not able to view your video

**Comment by Siddharth0328** [comment]
no bro it didnt work for you as I had closed the link by then. Maybe Ill create a new link and you can check if it works for you,coz no mater what im getting it as SITE CANT BE REACHED

**Comment by jaykali** [comment]
Makphish will work. Don't worry. Because Maskphish not modify the the URL. It  just shorten the URL and add some prefix (prefix will ignored by browser and browser will follow the shorten URL).

**Comment by Siddharth0328** [comment]
https://FaCeBoOk.com-trial@is.gd/C10hLa
Try this link out and let me know if it redirects you to facebook login page
