### ISSUE TITLE
Limited working of maskphish

### ISSUE THREAD

**Issue by Siddharth0328** [jaykali/maskphish#45]
The link works only if the victims mobile is connected to my mobile's hotspot. Other than that the masked link does not work

**Comment by jaykali** [comment]
**That is the problem you hosted your webpage locally not in internet.** _Maskphish works everywhere._  You need to learn the thing "`Phishing over WAN`".

**Comment by Siddharth0328** [comment]
Can u like me if I wanted to host in globally?

**Comment by jaykali** [comment]
Now how do we like you

**Comment by Siddharth0328** [comment]
Sorry bro. Can you help me if I wanted my phishing link to be accessed through wifi or mobile data

**Comment by jaykali** [comment]
First of all you need to learn the things. Try our this article and read carefully to understand what is ssh port forwarding. https://www.kalilinux.in/2019/07/port-forwarding-using-ssh.html
