### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by slythno** [jaykali/maskphish#53]
i'm using Termux maskphish isn't working no link generation

**Comment by jaykali** [comment]
Can you please provide the screenshot?

**Comment by slythno** [comment]
![Uploading IMG_20210719_102831.jpg…]()

**Comment by slythno** [comment]
![Uploading IMG_20210719_102831.jpg…]()

**Comment by slythno** [comment]
> Can you please provide the screenshot?
> 

![IMG_20210719_102831.jpg](https://user-images.githubusercontent.com/87435145/126106409-a718ec74-59cb-4e6d-9169-ff62d805f2b5.jpg)

**Comment by jaykali** [comment]
We tried yours. It is perfectly working here. You can try delete and reinstall it. Use this with a working internet connection. It should work. There isn't any error.
![maskphish](https://user-images.githubusercontent.com/62602243/126107081-ec989570-2ff2-42d9-8143-b2779b784894.png)
