### ISSUE TITLE
SORRY BRO ACTUALLY ITS NOT AN ISSUE 

### ISSUE THREAD

**Issue by just-hack** [jaykali/maskphish#6]
Its not an issue bro actually i wanted to know how you hosted "da.gd" can you please provide me the procedure bro so i can learn from it ,it will be very helpful bro . how i can i conatct you their was no other way so i contact you here sorry for it. awaiting for your reply

**Comment by jaykali** [comment]
We did not hosted it. [da.gd](https://da.gd/) is an open-source publicly available URL shorten service. We just use it. If you want to use it on your own hosting then the source code is available [here](https://github.com/dagd/dagd).

**Comment by jaykali** [comment]
and its sister not bro. LOL

**Comment by just-hack** [comment]
hahaha sorry for it ...so its open source ?? basically if i create one for me it wil be ga.gd or i can change that??

**Comment by jaykali** [comment]
You can't create ga.gd because this is a domain name owned by the creator. You need to buy your own. Code is available there. You need to modify it as per your requirements. Thanks
