### ISSUE TITLE
there is a @Error what should i do

### ISSUE THREAD

**Issue by Hackerv706** [jaykali/maskphish#65]
https://www.google.com-most-funny-video-ever@Error

**Comment by LakenCodes** [comment]
I am having the same problem also.

**Comment by jaykali** [comment]
![maskphish](https://user-images.githubusercontent.com/62602243/131339343-076c7da2-31a1-4aa3-a71a-f8ffff243ba6.png)
Here it's working perfectly here.
I think your ISP is blocking our services. Please try with VPN or proxychains.
