### ISSUE TITLE
Bad Subtitution 

### ISSUE THREAD

**Issue by karthikstech** [jaykali/maskphish#81]
Iam getting an error Bad Subtitution  or somethig like that after pasting the phishing link,please try to solve it,i can get you more details encluding a screenshot if needed.Btw,iam using zphisher,i tried with cludflare and also with ngrok,same issue.
Thanks.

**Comment by jaykali** [comment]
Ok. I got it. Please use `bash maskphish.sh` in the place of `./maskphish.sh`

This will solve your issue.
