### ISSUE TITLE
How do i fix this😔 or how do i move on from here?  It shows this https://mail.com-user@<!DOCTYPE html> and a long html coding below it. Link wont work on any browser  

### ISSUE THREAD

**Issue by Earlyangel** [jaykali/maskphish#85]
![Uploading Screenshot_20211231-053410_Termux.jpg…]()

Should I copy the html code below the link and save as txt .html and replace @<!DOCTYPE html> with document name and .html.

**Comment by jaykali** [comment]
Simply you can use `https://mail.com-user@your_url` . To give it more good look you can replace `your_url` to `your_shorten_url`
