### ISSUE TITLE
Mask phishing not working

### ISSUE THREAD

**Issue by mjain234** [jaykali/maskphish#88]
![Screenshot_2022-02-24-00-17-06-21_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/70900505/155387681-850fc807-391b-4759-8c4d-27c3ad5cc5e9.jpg)
Whenever I tried to mask any url, it shows at last @Blacklisted long url, how can I fix this issue? 
I have tried using VPN too but didn't help it out

**Comment by jaykali** [comment]
It seems you are using older version of MaskPhish. Remove it from your system and download it again it will work.
