### ISSUE TITLE
[BUG]Link not generated, Blacklisted long URL.

### ISSUE THREAD

**Issue by Bhaviktutorials** [jaykali/maskphish#9]
Error in Running your tool.
![Screenshot 2020-12-17 20:39:48](https://user-images.githubusercontent.com/64035221/102506076-c0e74f00-40a8-11eb-9efb-79100d795d80.png)
link not generating

**Comment by jaykali** [comment]
Thanks to notice this. Working on it.

**Comment by Bhaviktutorials** [comment]
Hello sir,
Would you like to collaborate sir?
We can try to fix this error together it would be help for me also and a great work together!!

**Comment by jaykali** [comment]
That link shorter service we are using is[ da.gd](https://da.gd) is blocking Ngrok urls. Searching for an good alternative.

**Comment by Bhaviktutorials** [comment]
I have found a alternative 
tny.im
can we start working on we just have to make a proper shell script to mask the domain!!!

**Comment by jaykali** [comment]
Hi, this is fixed. Please check it. If it is working again then please close this issue. Thanks

**Comment by jaykali** [comment]
Check it now. But in ZSH. Not working in BASH

**Comment by Bhaviktutorials** [comment]
Impossible sir 
Its working for me 
Can you connect to pc by TeamViewer sir? So I can show you 
You can msg me on whatsapp +91 91378 10819 sir

**Comment by Balaji-rocker** [comment]
its not working for me.
