### ISSUE TITLE
CopyRight Issue

### ISSUE THREAD

**Issue by rnsarker** [jaykali/maskphish#95]
This [person](https://github.com/OnlineHacKing) has copied your entire [code](https://github.com/OnlineHacKing/Masking-URL) and just replaced your name with his one. This copycat didn't even attributed your credit in his readme which directly violates your [license](https://github.com/jaykali/maskphish/blob/master/LICENSE). You should consider a [dmca takedown](https://docs.github.com/en/site-policy/content-removal-policies/dmca-takedown-policy) otherwise he will keep copying others

**Comment by jaykali** [comment]
Not only that. This guy is also copied our original [How to Hide Phishing Link](https://www.kalilinux.in/2020/07/how-to-hide-phishing-link.html) article, [in his article](https://www.onlinehacking.xyz/Hide-and-Charge-Any-Link) he forgot to change "MaskPhish" word... Funny haha.. We are taking steps. Thanks a lot for noticing that.

**Comment by Krovikan-Vamp** [comment]
Any update on this? Just curious.
