### ISSUE TITLE
Not being able to generate a full link

### ISSUE THREAD

**Issue by KarmaBait** [jaykali/maskphish#96]
Heyo, as some other users already stated it currently doesn't work if it comes to creating the full link.
It cuts of at the "@" and then just pastes a huge HTML code right behind it. 

Using a VPN (NordVPN, OpenVPN) has not fixed the issue.

 ### Masking Domain ###
Domain to mask the Phishing URL (with http or https), ex: https://google.com, http
://anything.org) :
=> https://instagram.com 

Type social engineering words:(like free-money, best-pubg-tricks)
Don't use space just use '-' between social engineering words
=> account-information

Generating MaskPhish Link...

Here is the MaskPhish URL: https://instagram.com-account-information@<!DOCTYPE HTML>                                                                    
<html lang="en-US">                                                         
<head>                                                                      
[LOTS OF HTML CODE]  
</html>

**Comment by badactorssuk** [comment]
Having same issue.

**Comment by Potatk** [comment]
same here

**Comment by jaykali** [comment]
Why? It is perfectly working on my machine..
- [Can someone please send me the output of following command in your terminal ]

`curl -s https://is.gd/create.php\?format\=simple\&url\=https://google.com`

**Comment by KarmaBait** [comment]
> Why? It is perfectly working on my machine..
> 
>     * [Can someone please send me the output of following command in your terminal ]
> 
> 
> `curl -s https://is.gd/create.php\?format\=simple\&url\=https://google.com`

sudo curl -s curl -s https://is.gd/create.php\?format\=simple\&url\=https://google.com

https://is.gd/jAxBiv

**Comment by jaykali** [comment]
Then MaskPhish will work perfectly. Please check it again.

**Comment by KarmaBait** [comment]
> Then MaskPhish will work perfectly. Please check it again.

Works now, after running "curl -s https://is.gd/create.php\?format\=simple\&url\=https://google.com".
Thank you!

**Comment by jaykali** [comment]
It should work every time. I believe that you have some other errors maybe some network or VPN issues. Closing this issue. Thanks.
